### PR TITLE
Added support for quad encoder + button input

### PR DESCRIPTION
**Pull request by lacklustrlabs**
* added a menu item that has a 'numeric modal' mode, in this mode it uses `next()` and `prev()` input to increase and decrease its numeric value. `select()` toggles the modal mode.
* added a menu item that only does 'MenuSystem::back()' when selected.
* made it possible for a menu item to change name at any time (by removing`const`from a few places). E.g. this way we can have menuitems that toggles start/stop etc, etc.  

With these changes it is possible to control the entire menu system with just`up`,`down`and`select` (or forward and backward rotation + a button)
I understand that these changes are quite extensive. And they could possibly have been implemented in a different way. This is just a suggestion.

regards
@eadf

### CODE REVIEW

**Comment by jonblack** [comment]
Thanks, this looks like a nice addition. I have some feedback for improvements. Let me know what you think.

1. Rather than using a define for the text buffer length, could we dynamically resize the buffer? I know it depends on what the formatter does, but it would be easier for users this way;
2. I think `menuSystemTextBuffer` should be a class member. As it stands, multiple `NumericMenuItem`'s will use the same buffer;
3. The `numberFormat` callback shouldn't take a non-const pointer to `menuSystemTextBuffer`. It's an internal implementation detail and giving the calling access to mess with it feels wrong. The formatter could return the formatted value instead (and give up ownership of it);
4. Instead of making `is_modal`, `modal_next`, and `modal_prev` public perhaps it's better to make `MenuSystem` a friend of `NumericMenuItem`, then they can be private. I can't see any reason for clients to call those functions;
5. I'm interested to know why you use the term `modal`? I think of dialogs when you say this;
6. Two public `add_item` methods will be really confusing for newcomers and beginners. Is there any way we can keep one `add_item` function. One option I thought of is to make the `on_select` callback a member of `MenuItem` and pass it in the constructor rather than in `MenuSystem::add_item`. The downside to that is that it's a breaking change.;
7. Why remove `const` from the return value of `get_selected`?

I'm sorry if that seems like a lot of suggestions. I'd love to know what you think; perhaps you have some other ideas?

Thanks again for the pull-request.

**Comment by eadf** [comment]
Don't worry, positive feedback like that is always positive :)

1. Normally I would have used a dynamically allocated buffer, but I'm a bit wary of memory leaks in a Arduino sketch. Without a proper debugger those bugs can be really nasty to get rid of.

2. In my first version`menuSystemTextBuffer`was a member, but I noticed that my available dynamic memory was dwindling quite fast with a few `NumericMenuItem`s. After some thoughts on the issue i realized that the buffer could be shared. Its an inherently single-threaded process and the content of the buffer is just sent to the LCD/Serial and then it could be wiped/reused.

3. Hm, true that. It could be up the user to handle the buffer entirely. Then we get rid of the need for the end user to modify MenuSystem.h too (MENUSYSTEM_TEXTBUFFER_SIZE). 

4. Good suggestion, I didn't know that Arduino c++ implemented friend. Apparently it is not as limited as I was informed.

5. Yes, it's from back in the days (96?) when I did some X11 programming. A modal dialog was something that was stealing all input until dismissed. Just like the `NumericMenuItem` do. Maybe it's not the correct term nowadays

6. `MenuItemBase` could be removed, and `BackMenuItem` could directly inherit from `MenuItem`.
Then a single add_item method should suffice:  
```void add_item(MenuItem* pItem, void (*on_select)(MenuItem*)=NULL)```
The price for this would be that `BackMenuItem` will contain a NULL `_on_select` pointer 99.9% of the time, but we will probably get a smaller vTable.

7. The problem was in in the`MenuSystem::next()`and`MenuSystem::prev()`methods. When in modal mode they delegate to the`NumericMenuItem::modal_next()`and`NumericMenuItem::modal_prev()`:
`_p_curr_menu->get_selected()->modal_next();`
Those methods can't operate on a`const`pointer because they modify`NumericMenuItem::_value`
The option I could think of was to use const-cast-away but that's inherently ugly imho. 

Please let me know what you think
I'll start with item 4 right away.

**Comment by jonblack** [comment]
That was fast. :) Changes look good. Comments for your comments:

1. That's a good point. I suppose my concern is that users need to know to define `MENUSYSTEM_TEXTBUFFER_SIZE` if they don't want the default. I wish the Arduino supported compile-time asserts. Perhaps I'll give dynamic allocation a try before releasing, but for now I guess documenting the requirement above is enough.
2. With some clever/complex state machines you could probably end up overwriting the buffer, but I agree it's very unlikely. Perhaps we could make the buffer a static member of `NumericMenuItem` so it's at least at the right scope?
3. Great!
4. I'm assuming friend is supported. I didn't think about it to be honest.
5. Ok. The term is fine. I couldn't think of anything else to call it to be honest.
6. Great idea. I think I'd prefer that.
7. Ok I understand. I think it's fine to remove the const. I prefer that over another method.

**Comment by eadf** [comment]
Thank you. I made some final modifications:

(1) I can't really figure out a good way to solve the text buffer problem. 
If we let the user define the buffer, we need to accept a pointer to it in get_name().
Or we require the users to more or less copy&paste the code of NumericMenuItem::get_name() (as it is now) into their numberformatters..
Yes, Arduino IDE really needs a way to define compile flags..
 
Maybe a solution will turn up with time.

(2) I tried to move the buffer as a static member, but I can't figure out how to initialize it. Google says that static array members should be initialized with `a = {0,0,...};` but that's no good with arbitrary sizes.
A sure way of crashing the buffer is to call get_name() from within the number format method. 
I added a method get_base_name() as a workaround for that (if someone needs the un-altered name) 

(5) Some variation of edit, edit mode or something could work as well. I'll leave it up to you to decide.

regards

**Comment by jonblack** [comment]
How does rebasing affect pull-requests? I've never tried it, but that might be a solition for cleaning up the history. I can rebase before merging to clean things up.

Thanks for the effort you put in. I'll grab the changes and run some tests and perhaps try dynamic allocation with `char*`, and then merge with master.

**Comment by eadf** [comment]
> How does rebasing affect pull-requests? I've never tried it, but that might be a solution for cleaning up the history. I can rebase before merging to clean things up.

I'm not sure about that. But it would be nice if you could rebase before merging. 

> Thanks for the effort you put in. I'll grab the changes and run some tests and perhaps try dynamic allocation with char*, and then merge with master.

I noticed that I used some camelCaseNaming inside NumericMenuItem (maxValue, minValue numberFormat). I would not mind if you renamed those.

**Comment by jonblack** [comment]
No worries, I'll take care of that too.

**Comment by jonblack** [comment]
I've started merging this today. I changed the callback function to `typedef String (*NumberFormat_t)(const float value);`. I think it's more descriptive passing the value rather than the whole item.

I'm trying to find a way to not have `get_composite_name` because it sounds too much like `get_name` and it only really applies to `NumericMenuItem`. It's not so easy though and may be something that I can solve with `display()` from #18.

**Comment by eadf** [comment]
> I changed the callback function to typedef String (*NumberFormat_t)(const float value);. I think it's more descriptive passing the value rather than the whole item.

By passing the String by reference I tried for these goals:
* As few alloc/dealloc and copy operations as possible. By passing by value, the String will be stack allocated and copied at least two times. Bad news for my 8MHz pro mini :)
* If really needed, the format function could govern more than just the number format. 
  By overwriting the String (instead of just appending) it could alter the entire text line. i.e. the "menu name=<" part. (but not the last ">").
 That's why it had access to the NumericMenuItem reference.

The _const_ in `const float value` is pointless, It's just a copy and after the format call the float doesn't exist any more.

> I'm trying to find a way to not have get_composite_name because it sounds too much like get_name and it only really applies to NumericMenuItem.

I started with having the `get_composite_name` functionality inside `get_name` but that didn't make sense when I really needed to retrieve the unaltered name. If there is a `set_name` then `get_name` should return the same value imho. 
Maybe you could replace `get_composite_name` with `get_text`,`get_line`or`get_representation`?
Or if that doesn't work: `get_name` and `set_name` could be renamed `get_base_name` and `set_base_name`. Then `get_composite_name`->`get_name`

**Comment by jonblack** [comment]
> If really needed, the format function could govern more than just the number format. By overwriting the String (instead of just appending) it could alter the entire text line. i.e. the "menu name=<" part. (but not the last ">" in modal mode). That's why it had access to the NumericMenuItem reference.

This is what #18 will help with. It defines a display callback for all Menu's. That callback will determine how to display the MenuItems in that menu. (It also might allow for removing the need for the client to ever trigger rendering itself). Plus, if you can do more than format the number, it's not really a number formatter anymore. I know, I know that's really pedantic of me.

> The const in const float value is pointless

It shows intent and will complain at compile time if users (think beginners) try to mess with it. You're right that it doesn't really matter.

> As few alloc/dealloc and copy operations as possible. By passing by value, the String will be allocated and copied at least two times. Bad news for my 8MHz pro mini :)

I knew you'd bring this up :smile: I was thinking the same, but I'm heading in the direction of not using String at all if I can because it's less memory efficient. I want to look at it with #18, but perhaps we'll need to go back to the parametrised variant. I'm open to it.

>and should* be the polymorphic goto method for text representation of any MenuComponent

And I think this comment touches on something we need to think about for #18. What is the polymorphic method for rendering a `MenuItem`. Should this be the user defined `display` callback? What will it look like? At the moment we're forcing a certain style (the '>' and '=' symbols).

How do feel about me finishing tidying up, rebasing and merging the code for this (with the changes mentioned above) with master, closing this issue, and moving the discussion over to #18?

**Comment by eadf** [comment]
> How do feel about me finishing tidying up, rebasing and merging the code for this (with the changes mentioned above) with master, closing this issue, and moving the discussion over to #18?

Sounds good, see you on the flip side

**Comment by jonblack** [comment]
I merged this into master. Perhaps I screwed something up with the rebasing :worried: since it didn't close this issue automatically. We'll see. In any case, the master branch works as expected.

**Comment by eadf** [comment]
Yeah, github thinks this PR is rejected.. but never mind that, the addon seems to work and that's the important bit.

**Pull request closed without merging**
