### PR TITLE
Add is_current to MenuComponent and add min, max parameters in set_value

### PR DESCRIPTION
**Pull request by arneboon**
Hi dear Jon,

Thanks for the awesome library! It is beautiful.

For writing only the current highlighted menu item to a lcd display, i needed an is_current function implemented. I am using it in the render like this:
```cpp
void MyRenderer::render_numeric_menu_item(NumericMenuItem const& menu_item) const
{
    String buffer;

    buffer = menu_item.get_name();
    buffer += menu_item.has_focus() ? '<' : '=';

    // TODO: get_value_string is a poor name. get_formatted_value maybe?
    buffer += menu_item.get_value_string();

    if (menu_item.has_focus())
        buffer += '>';

    Serial.print(buffer);
    
    if(menu_item.is_current()) {
        lcdDisplayPtr->printTopline(menu_item.get_name());
        
        String lcdBuffer;
        lcdBuffer += menu_item.has_focus() ? '<' : '=';
        lcdBuffer += menu_item.get_value_string();
        if (menu_item.has_focus()) {
            lcdBuffer += '>';
        }
        lcdDisplayPtr->printBottomline(lcdBuffer);
    }
}
```

Also i needed to set the min and max values during runtime. See the separate commit.

Here you find the pull request with these additions, for you to consider this merge request.

Thanks you and best regards,
Arne.

### CODE REVIEW

**Comment by jonblack** [comment]
Thanks! This was on my list. :smile: The `is_current` part looks fine.

I think it's better to have separate `set_min_value` and `set_max_value` methods instead of adding parameters to `set_value`.

**Comment by arneboon** [comment]
Hi Jon,

Ok thats great!

Thanks again for this very useful library.

**Comment by jonblack** [comment]
I had another look and there are some more issues:

1. The `MenuComponent` abstract base class doesn't have a concept of next and prev, only `Menu` has that. I'd remove `set_previous` and change `set_current` to `set_current(bool is_current=true)`;
2. When the system first loads no component has its `_is_current` set to `true` (see `Menu::add_item` and `Menu::add_menu`);
3. When a `Menu` is reset, only the first `MenuComponent` should has `_is_current` set to `true` (see `Menu::reset`);

There are also some examples that can be updated to use `is_current` instead of comparing pointers:

* serial_nav
* current_menu

Would you be able to fix these?

**Comment by jonblack** [comment]
Whatever GitHub. I made the proposed changes myself and merged the result, squashing all the commits. GitHub never seems to figure that out.

**Comment by arneboon** [comment]
Hello dear Jon,

Sorry for a late reply. Great you got this done! Thanks for your effort.

Best regards,
Arne.

**Pull request closed without merging**
